steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}', '--build-arg','BUILDPLATFORM=${_BUILDPLATFORM}', '.' ]
  env:
    - 'DOCKER_BUILDKIT=1'
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'

substitutions:
  _LOCATION: "us-central1"
  _REPOSITORY: "cloudrun-demo"
  _IMAGE: "image"
  _BUILDPLATFORM: "linux/amd64"
