steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
  env:
  - 'BUILDPLATFORM=linux/amd64'
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

substitutions:
  _LOCATION: "us-central1"
  _REPOSITORY: "cloudrun-demo"
  _IMAGE: "image"
