steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
             'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudrun-demo/myimage:${SHORT_SHA}', '.', '-f', 'dockerfile-admin']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudrun-demo/myimage:${SHORT_SHA}']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run', 'deploy', 'cloudrun-demo', '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
